### ISSUE TITLE
Following on the question 

### ISSUE THREAD

**Issue by danyaljj** [wasiahmad/Mining-Wikipedia#1]
@wasiahmad thanks for suggesting the idea. 

What is your algorithm for connecting articles to their categories, and how does it differ from the API results? 

This is what I have extracted from your data: 
```xml
<page id="598081" title="Saint Louis University">
	<categories>Saint Louis University, Jesuit universities and colleges in the United States, Roman Catholic universities and colleges in the United States, Universities and colleges in St. Louis, Missouri, Schools of public health in the United States, Educational institutions established in 1818, Roman Catholic universities and colleges in Missouri, Association of Catholic Colleges and Universities, Roman Catholic Archdiocese of St. Louis, 1818 establishments in Missouri Territory</categories>
</page>
```

While this is what api gives me: 
https://en.wikipedia.org/w/api.php?format=json&action=query&prop=categories&titles=Saint%20Louis%20University

**Comment by wasiahmad** [comment]
I am not sure whether it differs from API results but i didn't use that API as i have mentioned previously. There is no such algorithm to connect articles with categories as articles are already tagged with categories which i extracted from Wiki dump. Since i had to extract the entire category hierarchy from Wiki, i preferred offline manner rather than API call.

Main objective of this project was to extract the entire category taxonomy of Wikipedia so that i can establish some relationship between Wiki concepts. Here Wiki concepts mean Wiki article titles. Wiki concepts can have overlapped categories. If there is no overlapped category, we can still find some relationship between two concepts by computing the LCS distance of their relevant categories.

So the essence is, you can compute different type of relationship score between Wiki concepts if you have the category taxonomy and to extract that from Wiki dump was the main objective of this project.
